# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: server.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class Text2ImageServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/twirp.server.Text2Image"
		self._endpoints = {
			"DiffusionModel": Endpoint(
				service_name="Text2Image",
				name="DiffusionModel",
				function=getattr(service, "DiffusionModel"),
				input=_sym_db.GetSymbol("twirp.server.String"),
				output=_sym_db.GetSymbol("twirp.server.Bytes"),
			),
		}

class Text2ImageClient(TwirpClient):

	def DiffusionModel(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/twirp.server.Text2Image/DiffusionModel",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("twirp.server.Bytes"),
			**kwargs,
		)
